name: Build And Release

on:
    push:
        branches:
            - main

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.TOME_READ_WRITE_DOCKER_PAT }}
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  platforms: linux/arm64
                  push: true
                  tags: user/app:latest
            - name: Print package information
              run: |
                  echo "Package name: ${{ github.event.package.package_version.name }}"
                  echo "Package version: ${{ github.event.package.package_version.version }}"
            - name: Trigger Coolify deployment
              run: |
                  curl --request GET '${{ secrets.TOME_DEPLOY_WEBHOOK_URL }}' --header 'Authorization: Bearer ${{ secrets.TOME_DEPLOY }}'
