name: Docker Build and Release

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    build-and-release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4.1.7

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3.6.1

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3.3.0
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.TOME_READ_WRITE_DOCKER_PAT }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v6.5.0
              with:
                  context: .
                  push: true
                  tags: ghcr.io/${{ github.repository_owner }}/tometracker:latest

            - name: Image digest
              run: echo ${{ steps.docker_build.outputs.digest }}
            - name: Trigger Deploy
              env:
                  TOME_DEPLOY_WEBHOOK_URL: ${{ secrets.TOME_DEPLOY_WEBHOOK_URL }}
                  TOME_DEPLOY: ${{ secrets.TOME_DEPLOY }}
              run: |
                  curl -X POST \
                    -H "Content-Type: application/json" \
                    -H "Authorization: Bearer $TOME_DEPLOY" \
                    -d '{"event_type": "package_published"}' \
                    $TOME_DEPLOY_WEBHOOK_URL
