name: Issue Duplicate/Wontfix Automation
on:
    issues:
        types: [labeled]
jobs:
    handle_labeled_issue:
        if: github.event.label.name == 'duplicate' || github.event.label.name == 'wontfix'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4.1.7
            - name: Comment and close issue
              uses: actions/github-script@v7.0.1
              with:
                  github-token: ${{ secrets.MY_PAT }}
                  script: |
                      let comment = '';

                      if (context.payload.label.name === 'duplicate') {
                          comment = '👀 This issue has been identified as a duplicate. The original issue will be used for tracking and updates. Closing this issue to keep things tidy!';
                      } else if (context.payload.label.name === 'wontfix') {
                          comment = '🙏 Thanks for reporting this issue. After careful consideration, we've decided to mark this issue as `wontfix`. This could be due to the reported issue being expected behaviour or otherwise. @tommerty may add an additional comment shortly outlining the specifics.';
                      }

                      await github.rest.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: comment
                      });

                      await github.rest.issues.update({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        state: 'closed'
                      });
